### ISSUE TITLE
Tombol Logout yang Agak Sedikit Susah Dicari

### ISSUE THREAD

**Issue by jefrydco** [kharisma-wardhana/vue3-carbon-clone#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Kharisma. Mas juga sudah menambahkan Tailwind CSS sebagai kerangka kerja gayanya. Selain itu Mas juga menambahkan Vue Router, keren Mas! Tambahan lain yang menurut saya menarik juga adalah menyimpan data user secara lokal di peramban, sehingga ketika user memuat halamannya, user masih dalam keadaan login. Sering juga saya melupakan hal tersebut. :smile: 

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan yakni tombol logout yang agak sedikit susah dicari, awalnya saya kira kalau mengklik nama yang ada di navbar akan memunculkan dropdown opsi untuk logout. Ternyata yang harus diklik adalah logo github nya.

Mungkin logo GitHub tersebut bisa diarahkan ke repositori ini Mas, sedangkan untuk opsi tombol logout diganti ketika mengklik username. Dan di sebelah username tersebut diberi icon chevron bawah seperti ini untuk mengindikasikan dropdownnya:

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96430842-e254c780-122c-11eb-86a3-af58434633c0.png)

Eh satu lagi Mas, Mas udah bikin proyek ini menggunakan Vue 3, keren banget Mas! Mungkin dibagian `<script>` nya Mas bisa coba-coba eksperimen menggunakan Vue Composition API, saya cek di beberapa bagian masih menggunakan Options API. :smile: 

Semangat selalu ya! :muscle:

**Comment by kharisma-wardhana** [comment]
Terima kasih atas sharing ilmu dan sarannya mas,,
